name: ci

on:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.5
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yahuiwong/qq:${{ steps.branch-name.outputs.current_branch }}-${{ steps.commit.outputs.short }}

