name: publish-tags

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Tags Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yahuiwong/qq:${{steps.tag.outputs.tag}}
      -
        name: latest Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yahuiwong/qq:latest
